version: 2.1

orbs:
  node: circleci/node@4.7.0

executors:
  node:
    docker:
      - image: cimg/base:stable 

jobs:
  example-job:
    executor: node
    steps:
      - node/install:
          lts: false 
          node-version: '16.11' 
          npm-version: '8.1.3' 

workflows:
  example-workflow:
    jobs:
      - example-job
      - node/test
      - node/run:
          npm-run: build
        