version: 2.1

orbs:
  node: circleci/node@4.7.0

executors:
  node:
    docker:
      - image: cimg/base:stable 

commands:
  install:
    steps:
      - node/install:
          lts: false 
          node-version: '16.11' 
          npm-version: '8.1.3'


jobs:
  install:
    executor: node
    steps:
      - node/install:
          lts: false 
          node-version: '16.11' 
          npm-version: '8.1.3'

  test: 
    executor: node
    steps:
      - checkout
      - install
      - run:
          name: Test
          command: npm run test

  build:
    executor: node
    steps:
      - checkout
      - install
      - run:
          name: Build
          command: npm run build

  release:
    executor: node
    steps:
      - checkout
      - install
      - run:
          name: Release
          command: npm run release
    

workflows:
  example-workflow:
    jobs:
      - install
      - test:
          requires:
            - install
      - build:
          requires:
            - install
      - release:
          requires:
            - install
            - test
            - build
      