version: 2.1
orbs:
  node: circleci/node@4.7.0

executors:
  node:
    docker:
      - image: cimg/node:16.13.0

jobs:
  release:
    executor: node
    steps:
      - checkout
      - node/install
      - node/install-packages # Install and automatically cache packages
      # Run optional required steps before releasing
      - run: npm run build
      - run: npm run release
workflows:
  test_and_release:
    # Run the test jobs first, then the release only when all the test jobs are successful
    jobs:
      - node/test
      - release:
          requires:
            - node/test